# Generated by Django 5.1 on 2024-08-30 13:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('contato_principal', models.CharField(max_length=255)),
                ('contato_secundario', models.CharField(blank=True, max_length=255, null=True)),
                ('proposta_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_servico', models.CharField(choices=[('Regulatório', 'Regulatório'), ('Qualidade', 'Qualidade'), ('Capacitação e Treinamento', 'Capacitação e Treinamento'), ('Consultoria Empresarial', 'Consultoria Empresarial'), ('Suporte Pós Serviço', 'Suporte Pós Serviço')], max_length=50)),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo_execucao', models.IntegerField(help_text='Prazo em dias')),
            ],
        ),
        migrations.CreateModel(
            name='Suporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor_hora', models.DecimalField(decimal_places=2, default=75.0, max_digits=10)),
                ('data_suporte', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('coleta_informacoes', 'Coleta de Informações'), ('execucao', 'Execução'), ('aprovacao_cliente', 'Aprovação Cliente'), ('concluido', 'Concluído'), ('encerrado', 'Encerrado')], default='iniciado', max_length=50)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('data_fim_real', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_relatorio', models.TextField()),
                ('data_relatorio', models.DateField(default=django.utils.timezone.now)),
                ('tipo_relatorio', models.CharField(choices=[('impressao', 'Impressão'), ('excel', 'Excel')], max_length=50)),
                ('filtro', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.cliente')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.tarefa')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_etapa', models.CharField(max_length=255)),
                ('data_etapa', models.DateField(blank=True, null=True)),
                ('status_etapa', models.BooleanField(default=False)),
                ('observacoes_etapa', models.TextField(blank=True, null=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.tarefa')),
            ],
        ),
    ]
