# Generated by Django 5.1 on 2024-08-31 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='nome',
        ),
        migrations.AddField(
            model_name='servico',
            name='cliente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='workflow.cliente'),
            preserve_default=False,
        ),
    ]
