# Generated by Django 5.1 on 2024-12-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_servico_descricao_alter_tarefa_tipo_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervico',
            name='orgao',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
