# Generated by Django 5.1 on 2024-12-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_tarefa_valor_total_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='hora_fim',
            field=models.TimeField(blank=True),
        ),
    ]
