# Generated by Django 5.1 on 2024-09-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_remove_servico_prazo_execucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='prazo_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
