# Generated by Django 5.1 on 2024-09-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_servico_prazo_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
