# Generated by Django 5.1 on 2024-09-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_alter_servico_valor_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='data_fim_prevista',
            new_name='prazo_final',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='data_fim_real',
        ),
    ]
