# Generated by Django 5.1 on 2025-02-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_rename_fantasia_cliente_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('data_vencimento', models.DateField()),
                ('tipo_licenca', models.CharField(default='OUTRO', max_length=20)),
                ('renovacao_iniciada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='workflow.cliente')),
            ],
        ),
    ]
