# Generated by Django 5.1 on 2025-03-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_historicostatustarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='suporte',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
