# Generated by Django 5.1 on 2025-03-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_suporte_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='suporte',
            name='tempo_suporte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
