# Generated by Django 5.1 on 2025-03-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_suporte_tempo_suporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicostatustarefa',
            name='status',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('Coleta De Informações', 'Coleta de Informações'), ('Execucao', 'Execução'), ('Aprovação Cliente', 'Aprovação Cliente'), ('Concluído', 'Concluído'), ('Encerrado', 'Encerrado'), ('Protocolado', 'Protocolado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('Coleta De Informações', 'Coleta de Informações'), ('Execucao', 'Execução'), ('Aprovação Cliente', 'Aprovação Cliente'), ('Concluído', 'Concluído'), ('Encerrado', 'Encerrado'), ('Protocolado', 'Protocolado')], default='iniciado', max_length=50),
        ),
    ]
